version: '3'
services:
  buster-js-app:
    image: buster-js-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '4242'
    environment:
      NODE_ENV: dev
      BUSTER_API_URL: http://34.102.239.194
      LOCAL_SERVICE_URL: 127.0.0.1:883
    command: >
      bash -c "
      ./bin/wait-for-it.sh buster-app-mysql:3306 &&
      ./node_modules/.bin/db-migrate up &&
      ./node_modules/.bin/nodemon --watch 'src/**/*.ts' src/index.ts"
    depends_on:
      - buster-app-mysql
    volumes:
      - ./src:/opt/app/src
      - ./test:/opt/app/test
      - ./migrations:/opt/app/migrations
      - ./config:/opt/app/config
      - ./bin:/opt/app/bin
      - ./package.json:/opt/app/package.json
      - ./yarn.lock:/opt/app/yarn.lock
      - ./database.json:/opt/app/database.json
  buster-python-app:
    image: buster-python-app
    build:
      context: .
      dockerfile: python.Dockerfile
    ports:
      - '8082'
    environment:
      BUSTER_API_URL: http://34.102.239.194
    command: "python app.py"
    depends_on:
      - buster-app-mysql
    volumes:
      - ./python:/opt/app
  buster-java-app:
    image: buster-java-app
    build:
      context: java
      dockerfile: Dockerfile
    ports:
      - '8080'
    environment:
      BUSTER_API_URL: http://34.102.239.194
      SPRING_DATASOURCE_URL: jdbc:mysql://buster-app-mysql:3306/buster_dev
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - buster-app-mysql
  buster-app-mysql:
    image: 'mysql:5.7'
    command: "--character-set-server='utf8mb4' --collation-server='utf8mb4_unicode_ci'"
    ports:
      - '3306'
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: buster_dev
  buster-ngrok:
    image: 'wernight/ngrok'
    links:
      - buster-java-app
    environment:
      NGROK_PORT: buster-java-app:8080
    ports:
      - '4040'
